### ISSUE TITLE
Extracting neighbors for query set

### ISSUE THREAD

**Issue by jaredcthomas** [cmuparlay/ParlayANN#1]
Is it possible to save the nearest neighbors after querying (not just performance metrics)?

**Comment by magdalendobson** [comment]
Thanks for pointing out this issue and sorry for the delay as your question coincided with summer vacations. Currently we don't provide this functionality, but we're adding it to the to-do list for our upcoming refactor. 

In the meantime, I think it wouldn't be too tricky to repurpose the functions in the file parsing code, or to simply write the ids out to a sequence and use the parlay function writeIntSeqToFile, or similar.

**Comment by magdalendobson** [comment]
We just added the ability to save the groundtruth in binary to a file by adding a save function to the GroundTruth object.
