### ISSUE TITLE
Are there any benchmark results for the memory-constrained setting?

### ISSUE THREAD

**Issue by s-jse** [cmuparlay/ParlayANN#16]
Hi,

I was wondering if you have tested your implementation on a machine with limited RAM, where most of the index has to be kept on disk? Especially for DiskANN, which was originally designed to work well in this setting.

**Comment by magdalendobson** [comment]
Hi! Currently the library supports in-memory search only and we don't have an SSD-optimized graph search routine. If you do any benchmarking of this manner using ParlayANN, we would love to hear about it.
