### ISSUE TITLE
infinite loop in Vamana graph construction when n is small

### ISSUE THREAD

**Issue by yushangdi** [cmuparlay/ParlayANN#9]
When the input data size is very small,  `max_batch_size`  [here](https://github.com/cmuparlay/ParlayANN/blob/main/algorithms/vamana/index.h#L222) can be 0, and lead to an infinite loop.

**Comment by yushangdi** [comment]
one easy fix could be to add the following?

```
    if(max_batch_size == 0){
      max_batch_size = n;
    }
  ```

**Comment by magdalendobson** [comment]
Thanks for pointing this out. It is now fixed on main.
